version: 2

project_name: gplace

builds:
  - id: gplace
    main: ./cmd/gplace
    binary: gplace
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
      - windows_arm64
    ldflags:
      - -s -w -X github.com/qztseng/gplace/internal/cli.Version={{.Version}}

archives:
  - id: gplace
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: gplace
    description: "Modern Go client + CLI for the Google Places API (New)."
    homepage: "https://github.com/qztseng/gplace"
    license: "MIT"
    repository:
      owner: qztseng
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    install: |
      bin.install "gplace"
    test: |
      system "#{bin}/gplace", "--version"
